version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: cherubino-whisparr_server_1
      APP_PORT: 6969

  server:
    image: ghcr.io/thespad/whisparr:v3.6.1-release.1708-spad54
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure
